name: Deploy to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write     # needed for configure-pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies & build
        run: |
          npm ci
          npx webpack --config webpack.config.js

      # ———————————————
      # 1) Tell GitHub we’re doing a Pages deployment
      - name: Configure Pages
        uses: actions/configure-pages@v3

      # 2) Upload the built files as an “artifact”
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      # 3) Deploy the artifact to Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
